import moment from "moment/moment";
export const tempGreaseTraps = [
    {
      jobId: 12357,
      jobStatus: 'green',
      restrauntName: 'Layali Al Shams Royal',
      address: 'Zone 3 - Karama',
      noOfTraps: 2,
      capacity: 1800,
      createdAt: moment().format('DD-MM-YYYY HH:mm:ss'),
    },
    {
      jobId: 12358,
      jobStatus: 'orange',
      restrauntName: 'Layali Al Shams Royal',
      address: 'Zone 3 - Karama',
      noOfTraps: 2,
      capacity: 1800,
      createdAt: moment().format('DD-MM-YYYY HH:mm:ss'),
    },
    {
      jobId: 12359,
      jobStatus: 'red',
      restrauntName: 'Layali Al Shams Royal',
      address: 'Zone 3 - Karama',
      noOfTraps: 1,
      capacity: 1800,
      createdAt: moment().format('DD-MM-YYYY HH:mm:ss'),
    },
    {
      jobId: 12360,
      jobStatus: 'orange',
      restrauntName: 'Layali Al Shams Royal',
      address: 'Zone 3 - Karama',
      noOfTraps: 1,
      capacity: 1800,
      createdAt: moment().format('DD-MM-YYYY HH:mm:ss'),
    },
    {
      jobId: 12361,
      jobStatus: 'green',
      restrauntName: 'Layali Al Shams Royal',
      address: 'Zone 3 - Karama',
      noOfTraps: 1,
      capacity: 1800,
      createdAt: moment().format('DD-MM-YYYY HH:mm:ss'),
    },
    {
      jobId: 12362,
      jobStatus: 'green',
      restrauntName: 'Layali Al Shams Royal',
      address: 'Zone 3 - Karama',
      noOfTraps: 1,
      capacity: 1800,
      createdAt: moment().format('DD-MM-YYYY HH:mm:ss'),
    },
    {
      jobId: 12363,
      jobStatus: 'red',
      restrauntName: 'Layali Al Shams Royal',
      address: 'Zone 3 - Karama',
      noOfTraps: 1,
      capacity: 1800,
      createdAt: moment().format('DD-MM-YYYY HH:mm:ss'),
    },
  ];